### ISSUE TITLE
Issues when trying to convert html to md

### ISSUE THREAD

**Issue by jmbenedetto** [rafalkaron/MarkUP#7]
Hello, Rafal.

Thanks a lot for your code. It will be very helpful on my workflow to convert html files (old Onenote exports) into markdow.

For now, I could not make it work:
* download the mac version.
* unzip the file at Downloads
* run ./markup "20110114_01.00 - Análise Estratégica - Meta Processo.html" html_md in terminal from Downloads

Result                                 
Traceback (most recent call last):
  File "__main__.py", line 55, in <module>
  File "__main__.py", line 49, in main
  File "MarkUP/convert.py", line 131, in html_md
  File "MarkUP/convert.py", line 96, in convert_file
  File "MarkUP/files.py", line 31, in save_str_as_file
OSError: [Errno 30] Read-only file system: '/20110114_01.00 - Análise Estratégica - Meta Processo.md'
[40098] Failed to execute script __main__

Expected result:
20110114_01.00 - Análise Estratégica - Meta Processo.md file created.

Could you please help me out?

Thanks again

**Comment by rafalkaron** [comment]
Hi @jmbenedetto,

Thank you for your interest in this project and for submitting the detailed issue. I could indeed reproduce it on my machine (M1 Pro).
I haven't contributed to this repo for a while and it looks like macOS has hardened its security settings in the meantime.

**Here's a workaround:** 
1. In Finder or Terminal, in your home directory, create a directory (for example: create an `output` directory).  
**NOTE:** Do not create directories with spaces or special symbols.
2. Run: `./markup "20110114_01.00 - Análise Estratégica - Meta Processo.html" html_md -out ~/output`  
**NOTE:** Do not put the `~/output` directory in quotation marks.

It looks like the macOS security is hardened for the "default" directories like `Downloads`, `Desktop`, or your home directory. Because of that, my app cannot write to these locations. That's why I suggested to create the `output` directory and tell the app to output the converted files there.

Please let me know if this resolves your issue! :)

**Comment by jmbenedetto** [comment]
Thanks a lot!

It worked for individual files, but I got an error message when trying to convert all files from a folder. See the message below:

```
(base) [jmbenedetto:~/code/markup]$ ./markup /Users/jmbenedetto/Documents/3_references/Strategy html_md --out ./markup/output
Traceback (most recent call last):
  File "__main__.py", line 55, in <module>
  File "__main__.py", line 49, in main
  File "MarkUP/convert.py", line 133, in html_md
  File "MarkUP/convert.py", line 72, in convert_folder
  File "MarkUP/files.py", line 31, in save_str_as_file
NotADirectoryError: [Errno 20] Not a directory: './markup/output/20120315_Livro - Michael Porter - Competitive Advantage.md'
[77210] Failed to execute script __main__
```

At any rate, I was able to do a batch conversion by not changing the output folder:

`./markup /Users/jmbenedetto/Documents/3_references/Strategy html_md `

Thanks a lot for your code :)
